### ISSUE TITLE
Journal Entry Form

### ISSUE THREAD

**Issue by MaggieSchuetz** [MaggieSchuetz/capstone-project#1]
## Value proposition

**As a** traveler
**I need to** record my travels in a convenient way
**to be able to** remember them

## Description
![Bildschirmfoto 2022-03-03 um 15 24 16](https://user-images.githubusercontent.com/70511409/156583989-4aa45211-b1b2-4d8a-aeea-d9db481cf5c6.png)

## Acceptance Criteria

- [ ] The user is presented with a form and an empty journal
- [ ] If the journal is empty, there should be a message that there are no entries yet
- [ ] The user can add a journal entry by entering date, title and some text into the form
    - [ ] Title is required and can be no longer than 40 characters
    - [ ] Date is required and should be in the date format
    - [ ] Text is required (no minimum, no maximum)
- [ ] After submitting, the item should be added to the JournalList

## Tasks

- [ ] Global Styles
- [ ] Create component/JournalForm
   - [ ] Write tests
   - [ ] Storybook
   - [ ] Add styled components
- [ ] Create component/Button
   - [ ] Write tests
   - [ ] Storybook
   - [ ] Add styled components
- [ ] Create component/JournalList
   - [ ] Write tests
   - [ ] Storybook
   - [ ] Add styled components
- [ ] Create component/Card
   - [ ] Write tests
   - [ ] Storybook
   - [ ] Add styled components
- [ ] Add to App
- [ ] Check accessibility
- [ ] Check on mobile device
