### ISSUE TITLE
Add photo upload

### ISSUE THREAD

**Issue by MaggieSchuetz** [MaggieSchuetz/capstone-project#16]
### Value Propositions

**As a** user
**I need to** be able to upload and display photos
**To be able to** create better memories of my trips

### Description 

<img width="460" alt="Bildschirmfoto 2022-03-14 um 10 49 50" src="https://user-images.githubusercontent.com/70511409/158147702-44feac93-2ede-4087-9f46-e79ca3f79295.png">

### Acceptance criteria

- [ ] The form displays an "Add photos" button
- [ ] This button opens a photo upload 
- [ ] Multiple files can be selected
- [ ] Photos are uploaded
- [ ] The form displays a message about the status of the upload ("Still uploading" / "Upload successful")
- [ ] After clicking submit, photos are displayed on the correct journal entry card
- [ ] Photos are formatted so that they look the same on each journal entry

### Tasks

- [ ]  Create addPhoto Button
    - [ ] Write tests
    - [ ] Storybook
    - [ ] Styled-components
    - [ ] Add to Form

- [ ] Create photo upload process
- [ ] Render journal entry cards with photos
