### ISSUE TITLE
Add tags

### ISSUE THREAD

**Issue by MaggieSchuetz** [MaggieSchuetz/capstone-project#18]
## Value Propositions

**As a** user
**I need to** be able to add tags
**To be able to** more easily get an overview what my journal entries are about

## Description
![Bildschirmfoto 2022-03-16 um 11 16 05](https://user-images.githubusercontent.com/70511409/158567831-744f812f-5add-4aa4-902a-eeee24bfdfde.png)

## Acceptance Criteria
- [ ]  The form contains a new input field for tags
- [ ]  Tags are separated by comma
- [ ]  Tags are rendered in the journal entries

## Tasks
- [ ]  Add input field for tags
    - [ ]  Storybook
    - [ ] Test
- [ ]  Render tags on journal entry
    - [ ]  Storybook
    - [ ] Test
