### ISSUE TITLE
Add search by tag

### ISSUE THREAD

**Issue by MaggieSchuetz** [MaggieSchuetz/capstone-project#19]
## Value Propositions

**As a** user
**I need to** be able to search by tags
**To be able to** more easily find the journal entry I am looking for 

## Description

![Bildschirmfoto 2022-03-16 um 11 25 34](https://user-images.githubusercontent.com/70511409/158569585-f6151d3f-777b-48f5-a418-449f23e7373b.png)
## Acceptance Criteria

- [ ]  There is a new Route for search
- [ ]  The search page contains an input field where you can search for tags
- [ ] On "search", the user is presented with all journal entries that contain the tag they searched for

## Tasks
- [ ]  Create search page
    - [ ]  Storybook
    - [ ] Test
    - [ ] Add to App
- [ ]  Render entries that contain the tag under search form
    - [ ]  Storybook
    - [ ] Test
