### ISSUE TITLE
Editing the Card item

### ISSUE THREAD

**Issue by MaggieSchuetz** [MaggieSchuetz/capstone-project#2]
## Value proposition

**As a** user
**I need** edit my posts
**to be able to** correct mistakes or add details

## Description
![Bildschirmfoto 2022-03-03 um 15 51 45](https://user-images.githubusercontent.com/70511409/156589360-15fd667c-ee22-4eae-8d65-12a9251a007c.png)

## Acceptance Criteria

- [ ] Each Card contains an edit button
- [ ] If the edit button is clicked, the data from this Card is automatically input into the form, so that the user can edit it
- [ ] On submit, the edited Card replaces the old Card

## Tasks

- [ ] Create ButtonEdit
    - [ ] Write tests
    - [ ] Storybook
    - [ ] Add styled-components
- [ ] Copy information from Card into respective input fields
    - [ ] Write tests
- [ ] Add edited Card to Journal List, remove old Card from journal list
    - [ ] Write tests
