### ISSUE TITLE
Delete photos

### ISSUE THREAD

**Issue by MaggieSchuetz** [MaggieSchuetz/capstone-project#23]
## Value Propositions

**As a** user
**I need to** delete individual photos 
**To be able to** remove images  accidentally uploaded or no longer want in my post 

## Description
<img width="253" alt="Bildschirmfoto 2022-03-23 um 10 05 54" src="https://user-images.githubusercontent.com/70511409/159662864-804d4208-91b5-4dc0-956c-1579fc78c768.png">

## Acceptance Criteria

- [ ]  There is a delete button rendered on each image
- [ ] Clicking on "delete" will open a warning to ask if the user is sure they want to delete the image
- [ ] If the user decides to delete the image, it is no longer displayed in the journal entry

## Tasks
- [ ]  Create delete button for images
    - [ ]  Storybook
    - [ ] Test
    - [ ] Add to Images
