### ISSUE TITLE
Enlarge photos

### ISSUE THREAD

**Issue by MaggieSchuetz** [MaggieSchuetz/capstone-project#24]
## Value Propositions

**As a** user
**I need to** enlarge photos 
**To be able to** see them better

## Description

<img width="533" alt="Bildschirmfoto 2022-03-23 um 10 22 30" src="https://user-images.githubusercontent.com/70511409/159665971-ccd3131b-5e3e-491b-a38d-4b43c21f37db.png">

## Acceptance Criteria

- [ ]  A button is rendered on the gallery that signals it can be enlarged
- [ ]  When the user clicks on the gallery, it will expand
- [ ]  A button is rendered that can shrink the gallery again
- [ ] When the user clicks on it, the gallery shrinks back to normal size

## Tasks
- [ ]  Create enlarge / shrink button
    - [ ]  Storybook
    - [ ] Test
    - [ ] Add to Images
