### ISSUE TITLE
Map

### ISSUE THREAD

**Issue by MaggieSchuetz** [MaggieSchuetz/capstone-project#25]
## Value Propositions

**As a** user
**I need to** see a map and add markers to it
**To be able to** keep track of where I have been

## Description
<img width="250" alt="Bildschirmfoto 2022-03-23 um 10 33 26" src="https://user-images.githubusercontent.com/70511409/159668354-44b854db-0e5b-4f09-add6-39428e418d81.png">

## Acceptance Criteria

- [ ]  A new page with a map is rendered
- [ ] The map contains markers
- [ ] If you click on the marker, a field opens with the title of the journal entry
- [ ] If you click on the journal entry, the whole post opens

## Tasks
- [ ]  Create map page with markers
    - [ ]  Storybook
    - [ ] Test
    - [ ] Add to App
- [ ]  Create title card that leads to the specific post
    - [ ]  Storybook
    - [ ] Test
    - [ ] Add to map
