### ISSUE TITLE
Deleting a Card item

### ISSUE THREAD

**Issue by MaggieSchuetz** [MaggieSchuetz/capstone-project#3]
## Value proposition

**As a** user
**I need** to be able to delete cards
**to be able to** delete journal entries

## Description

![Bildschirmfoto 2022-03-04 um 15 12 27](https://user-images.githubusercontent.com/70511409/156778778-0d4f46c6-9108-49b0-8f02-72fcc87993f4.png)

## Acceptance Criteria
- [x] Card items contain a delete button
- [x] Clicking on the delete button opens a confirmation window "Delete this entry? Yes/No"
   - [x] If  "Yes" is clicked in the window, the Card item is removed from JournalList
   - [x] If "No" is clicked in the window, the Card item is not removed

## Tasks
- [x] Create Button delete 
    - [x] Write tests
    - [x] Storybook
    - [x] Styled-components
- [x] Remove Card item from Journal List (only) if delete=yes
