### ISSUE TITLE
Create a component/pages/Home

### ISSUE THREAD

**Issue by MaggieSchuetz** [MaggieSchuetz/capstone-project#4]
## Value proposition

**As a** user
**I need** to decide whether I want to read or write in my travel journal
**to be able to** have a better overview

## Description
![Bildschirmfoto 2022-03-03 um 17 09 24](https://user-images.githubusercontent.com/70511409/156606531-c616cd9f-2d4f-4c1d-86b8-9a50c16d3c76.png)

## Acceptance Criteria
- [ ]

## Tasks
- [ ] Create component/ButtonRead
    - [ ] Write tests
    - [ ] Storybook
    - [ ] Styled-components
- [ ] Create component/ButtonNewEntry
    - [ ] Write tests
    - [ ] Storybook
    - [ ] Styled-components
- [ ] Create component/pages/Home
    - [ ] Write tests
    - [ ] Storybook
    - [ ] Styled-components
    - [ ] Add to App 
- [ ] Add React Router and make component/pages/Home the default page
