### ISSUE TITLE
Create components/pages/NewEntry

### ISSUE THREAD

**Issue by MaggieSchuetz** [MaggieSchuetz/capstone-project#5]
## Value proposition

**As a** user
**I need** to be able to input my data in a separate page
**to be able to** have a better overview

## Description

![Bildschirmfoto 2022-03-03 um 17 41 02](https://user-images.githubusercontent.com/70511409/156610119-487b49be-c4c5-4fd4-9618-6acab31760ca.png)

## Acceptance Criteria
- [ ] The input form is on a separate page
- [ ] The route "/NewEntry" leads to this page

## Tasks
- [ ] Create component/Header
    - [ ] Write tests
    - [ ] Storybook
    - [ ] Styled-components
- [ ] Create component/pages/NewEntry
    - [ ] Write tests
    - [ ] Storybook
    - [ ] Styled-components
    - [ ] Add to App 
- [ ] Add React Router and route component/pages/NewEntry to this page
