### ISSUE TITLE
Create components/pages/JournalEntries

### ISSUE THREAD

**Issue by MaggieSchuetz** [MaggieSchuetz/capstone-project#6]
## Value proposition

**As a** user
**I need** to be able to view my journal entries on a separate page
**to be able to** have a better overview

## Description
![Bildschirmfoto 2022-03-03 um 17 37 56](https://user-images.githubusercontent.com/70511409/156611560-19ed4cce-7cb5-4207-82f7-50cd136c3752.png)

## Acceptance Criteria
- [ ] The journal entries are on a separate page
- [ ] The route "/JournalEntries" leads to this page

## Tasks
- [ ] Add component/Header
- [ ] Create component/pages/JournalEntries
    - [ ] Write tests
    - [ ] Storybook
    - [ ] Styled-components
    - [ ] Add to App 
- [ ] Add React Router and route component/pages/JournalEntries to this page
