### ISSUE TITLE
Create and add component/NavBar

### ISSUE THREAD

**Issue by MaggieSchuetz** [MaggieSchuetz/capstone-project#7]
## Value proposition

**As a** user
**I need**  a navigation bar
**to be able to** to navigate between reading and writing journal entries

## Description

![Bildschirmfoto 2022-03-03 um 17 53 46](https://user-images.githubusercontent.com/70511409/156612595-5c87099d-03b9-4975-86c8-fa32a591adbe.png)

## Acceptance Criteria
- [ ] The NavBar is displayed on the NewEntry and JournalEntries pages
- [ ] The NavBar routes correctly to both pages
- [ ] The currently active NavBarButton is highlighted

## Tasks
- [ ] Create component/pages/ButtonNavBar
    - [ ] Create active / inactive versions
    - [ ] Write tests
    - [ ] Storybook
    - [ ] Styled-components
    - [ ] Add to NavBar
- [ ] Create components/NavBar
    - [ ] Write tests
    - [ ] Storybook
    - [ ] Styled-components
    - [ ] Add to components/pages/NewEntry
    - [ ] Add to components/pages/JournalEntries
- [ ] On click, each button routes to the respective page
