### ISSUE TITLE
Add click to expand to components/Card

### ISSUE THREAD

**Issue by MaggieSchuetz** [MaggieSchuetz/capstone-project#8]
## Value proposition

**As a** user
**I need** to be able to expand my journal entries (and make them small again)
**to be able to** find things more easily without scrolling for too long

## Description
![Bildschirmfoto 2022-03-04 um 09 47 21](https://user-images.githubusercontent.com/70511409/156730156-9bff25c7-0572-493d-b421-f1ae5e5ed7a2.png)

## Acceptance Criteria

- [ ] Each Card item is the same size
- [ ] The text on each Card item stops after max. 150 characters WITHOUT truncating the last word 
- [ ] Each Card item displays a "Show more" button that expands the card to full size when clicked
- [ ] When the Card is fully expanded, the button reads "Show less"
- [ ] When "show less" is clicked, the card retracts to its original size

## Tasks
- [ ] Create a toggle component/ButtonShowMore
    - [ ] Write tests
    - [ ] Storybook
    - [ ] Styled-components
- [ ] Add to Card item
