### ISSUE TITLE
Store contents

### ISSUE THREAD

**Issue by MaggieSchuetz** [MaggieSchuetz/capstone-project#9]
## Value proposition

**As a** user 
**I need** to store my journal entries
**to be able to** access them when I want to

## Description
Create a local storage or backend

## Acceptance Criteria

- [ ] The input data remains accessible after reloading the page
- [ ] New input data will be stored and accessible after the next reload

## Tasks

- [ ] Create a local storage
    - [ ] Run tests
- [ ] Create a backend
    - [ ] Run tests
